[package]
name = "physics_engine"
version = "0.1.0"
edition = "2021"

[dependencies]
nalgebra = { workspace = true }
ndarray = { workspace = true }
rand = { workspace = true }
rand_chacha = { workspace = true }
rand_distr = { workspace = true }
serde = { workspace = true }
serde_arrays = { workspace = true }
anyhow = { workspace = true }
thiserror = { workspace = true }
rayon = { workspace = true }
ordered-float = { workspace = true }
approx = { workspace = true }
bevy_ecs = { workspace = true, optional = true }
once_cell = { workspace = true }
log = { workspace = true }
endf_parser = "0.2.0"

[features]
default = ["gpu-acceleration", "bevy"]
gpu-acceleration = []
simd = []
bevy = ["dep:bevy_ecs"]