[package]
name = "physics_types"
version = "0.1.0"
edition = "2021"

[dependencies]
nalgebra = { workspace = true }
serde = { workspace = true }
anyhow = { workspace = true }
thiserror = { workspace = true }
num-complex = { workspace = true } 