[package]
name = "universectl"
version = "0.1.0"
edition = "2021"
description = "Command-line interface for the Universe Simulation"

[[bin]]
name = "universectl"
path = "src/main.rs"

[dependencies]
universe_sim = { path = "../crates/universe_sim" }
clap = { workspace = true, features = ["derive"] }
tokio = { workspace = true, features = ["rt-multi-thread"] }
anyhow = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter"] }
serde = { workspace = true }
toml = { workspace = true }
tokio-tungstenite = "0.21"
warp = "0.3"
serde_json = { workspace = true }
futures-util = "0.3"
reqwest = { version = "0.11", features = ["json"] }
bincode = "1.3.3"
miniz_oxide = "0.7"
tracing-log = "0.1"