[package]
name = "viz_web"
version = "0.1.0"
edition = "2021"
description = "Web visualization for Evolve: The Game of Life"
license = "MIT OR Apache-2.0"

[dependencies]
universe_sim = { path = "../crates/universe_sim" }
macroquad = { workspace = true }
wasm-bindgen = { workspace = true }
web-sys = { workspace = true }