# Universe Simulation Default Configuration
# ========================================

# Time simulation parameters
tick_span_years = 100_000.0          # 1 million years per tick
target_ups = 1000.0                    # Updates per second target
# max_ticks = 0                         # No limit (infinite simulation) - 0 means infinite

# Initial conditions
initial_particle_count = 1000          # Starting particles after Big Bang
universe_radius_ly = 100.0            # Initial universe radius (light-years)
big_bang_temperature = 3000.0          # Initial temperature (K)

# Physics parameters
physics_timestep = 0.000001            # 1 microsecond integration timestep
enable_relativity = true               # Enable relativistic corrections
enable_quantum = true                  # Enable quantum effects
enable_chemistry = true                # Enable chemical reactions

# Agent evolution parameters
agent_mutation_rate = 0.001            # 0.1% probability per tick
max_agents_per_planet = 10000          # Population limit per planet
agent_lifespan_ticks = 1000            # Maximum individual lifespan (1 Gyr)
enable_self_modification = true        # Allow agents to modify their code

# Performance and resource limits
memory_limit_gb = 4.0                  # Memory usage limit (GB)
cpu_limit_percent = 70.0               # CPU usage limit (0-100%)
auto_save_interval = 10000             # Ticks between autosaves
auto_save_path = "./checkpoints/"      # Path for autosaved checkpoints
checkpoint_retention = 3               # Number of checkpoints to keep

# God-mode parameters
god_mode_enabled = false               # Disable divine intervention by default
max_miracles_per_epoch = 5             # Miracle limit per cosmic era
divine_entropy_cost = 100000000000000000000.0  # High entropy cost for miracles

# Networking and distribution
enable_clustering = false              # Single-node by default
cluster_node_limit = 16                # Maximum cluster nodes
enable_oracle_link = false           # Enable agent-operator communication

# Validation and safety
strict_physics_validation = false       # Enforce conservation laws strictly
enable_safety_guards = true            # Enable resource protection
# simulation_seed = 42                  # Random seed (commented out = random)