# Universe Simulation Low-Memory Configuration
# =============================================
# Optimized for Raspberry Pi 4 and similar devices

# Time simulation parameters
tick_span_years = 1_000_000.0          # 1 million years per tick
target_ups = 100.0                     # Lower UPS target for efficiency
max_ticks = null                       # No limit

# Initial conditions
initial_particle_count = 100           # Fewer particles for low memory
universe_radius_ly = 500.0             # Smaller universe
big_bang_temperature = 3000.0          # Standard temperature

# Physics parameters
physics_timestep = 0.00001             # Larger timestep for efficiency
enable_relativity = true               # Keep physics accurate
enable_quantum = false                 # Disable for performance
enable_chemistry = false               # Disable for performance

# Agent evolution parameters
agent_mutation_rate = 0.01             # Higher mutation rate for faster evolution
max_agents_per_planet = 1000           # Lower population limit
agent_lifespan_ticks = 500             # Shorter lifespan
enable_self_modification = true        # Keep evolution capability

# Performance and resource limits
memory_limit_gb = 0.5                  # 512 MB limit
cpu_limit_percent = 50.0               # Conservative CPU usage
auto_save_interval = 1000              # More frequent saves
checkpoint_retention = 3               # Fewer checkpoints

# God-mode parameters
god_mode_enabled = false               # Disabled
max_miracles_per_epoch = 2             # Fewer miracles
divine_entropy_cost = 100000000000000000000.0

# Networking and distribution
enable_clustering = false              # Single-node only
cluster_node_limit = 1                 # No clustering
enable_oracle_link = false             # Disable for performance

# Validation and safety
strict_physics_validation = false      # Relax validation for performance
enable_safety_guards = true            # Keep safety on
simulation_seed = null