[package]
name = "universe_sim"
version = "0.1.0"
edition = "2021"
description = "Core simulation engine for Evolve: The Game of Life"
license = "MIT OR Apache-2.0"

[dependencies]
bevy_ecs = { workspace = true }
rkyv = { workspace = true }
serde = { workspace = true }
tokio = { workspace = true }
rayon = { workspace = true }
nalgebra = { workspace = true }
rand = { workspace = true }
rand_chacha = { workspace = true }
thiserror = { workspace = true }
anyhow = { workspace = true }
log = { workspace = true }
sled = { workspace = true }

# Physics and chemistry
ndarray = { workspace = true }
ndarray-linalg = { workspace = true }
approx = { workspace = true }
num-traits = { workspace = true }
num-complex = { workspace = true }

# System integration
nix = { workspace = true }
libc = { workspace = true }

# Additional dependencies
serde_yaml = "0.9"
rand_distr = "0.4"

# Monitoring (optional)
prometheus = { workspace = true, optional = true }
sysinfo = { workspace = true, optional = true }

[dev-dependencies]
criterion = { workspace = true }
approx = { workspace = true }

[[bench]]
name = "physics_bench"
harness = false

[[bench]]
name = "ai_bench"
harness = false

[features]
default = ["validation"]
validation = []
metrics = ["prometheus", "sysinfo"]
low-mem = []
gpu-compute = []